name: Run e2e tests

on:
  schedule:
    - cron: '0 6 * * 1-5'
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Environment url'
        required: true
        default: 'http://localhost:3000'

jobs:

  execute_tests:
    name: Execute UI e2e tests

    strategy:
      matrix:
        node: [ '16' ]
    runs-on: ubuntu-latest

    env:
      BASE_BRIQ_URL: ${{ github.event.inputs.base_url || 'http://localhost:3000' }}
      CI: true
      DEBUG: pw:api

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      # - name: Run linter
      #   run: npm run lint
      - name: Install Playwright
        run: npx playwright install --with-deps > /dev/null
      - name: Run features
        run: npm run test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-result-report
          path: reports/report.html